version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mysql_default
      - leantime_default
      - n8n_default
      - nodered_default

volumes:
  caddy_data:
  caddy_config:

networks:
  mysql_default:
    external: true
  leantime_default:
    external: true
  n8n_default:
    external: true
  nodered_default:
    external: true

