version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: princ_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: princ_phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: princ_mysql
      PMA_AUTH_TYPE: http
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    name: mysql_default

